#!/usr/bin/env python3

import pytest

from astra_shared.custom_antenna_csv_parser import (
    CsvErrorCode,
    CustomAntennaCsvError,
    parse_custom_antenna_csv_text,
)
from astra_shared.custom_antenna_interpolation import lookup_custom_gain_db


def test_parse_valid_rectangular_csv_to_canonical_payload():
    text = """psi_deg,phi_deg,gain_dbi
0,0,30
0,180,20
10,0,15
10,180,5
"""
    payload = parse_custom_antenna_csv_text(text, filename="pattern.csv")
    assert payload["enabled"] is True
    assert payload["source_format"] == "csv"
    assert payload["filename"] == "pattern.csv"
    assert payload["psi_deg"] == [0.0, 10.0]
    assert payload["phi_deg"] == [0.0, 180.0]
    assert payload["gain_dbi"] == [[30.0, 20.0], [15.0, 5.0]]
    assert payload["validation"]["is_valid"] is False
    assert "missing_frequency_hz" in payload["validation"]["errors"]


def test_parse_supports_alias_headers_and_preamble_comments():
    text = """# generated by tool
; metadata line

 theta,azimuth_deg,gain_db
0,0,30
0,180,20
10,0,15
10,180,5
"""
    payload = parse_custom_antenna_csv_text(text)
    assert payload["psi_deg"] == [0.0, 10.0]
    assert payload["phi_deg"] == [0.0, 180.0]
    assert payload["gain_dbi"] == [[30.0, 20.0], [15.0, 5.0]]


def test_parse_skips_partial_metadata_header_before_real_header():
    text = """psi_deg,value
generated,example
psi_deg,phi_deg,gain_dbi
0,0,30
0,180,20
10,0,15
10,180,5
"""
    payload = parse_custom_antenna_csv_text(text)
    assert payload["psi_deg"] == [0.0, 10.0]
    assert payload["phi_deg"] == [0.0, 180.0]


def test_parse_header_token_normalization_accepts_case_space_dash_variants():
    text = """ Off Axis-Deg , Az Deg , GAIN-DB
0,0,30
0,180,20
10,0,15
10,180,5
"""
    payload = parse_custom_antenna_csv_text(text)
    assert payload["psi_deg"] == [0.0, 10.0]
    assert payload["phi_deg"] == [0.0, 180.0]


def test_parse_normalizes_negative_phi_to_zero_360_convention():
    text = """psi_deg,phi_deg,gain_dbi
0,-90,30
0,0,20
0,90,10
10,-90,15
10,0,5
10,90,1
"""
    payload = parse_custom_antenna_csv_text(text)
    assert payload["phi_deg"] == [0.0, 90.0, 270.0]
    assert payload["gain_dbi"] == [[20.0, 10.0, 30.0], [5.0, 1.0, 15.0]]


def test_negative_phi_grid_interpolates_across_zero_degree_seam():
    text = """psi_deg,phi_deg,gain_dbi
0,-90,30
0,0,20
0,90,10
10,-90,15
10,0,5
10,90,1
"""
    payload = parse_custom_antenna_csv_text(text)
    payload["validation"]["is_valid"] = True
    assert lookup_custom_gain_db(0.0, 359.0, payload) == pytest.approx(20.1111111111)
    assert lookup_custom_gain_db(0.0, 1.0, payload) == pytest.approx(19.8888888889)


@pytest.mark.parametrize(
    ("text", "code"),
    [
        ("psi_deg,phi_deg\n0,0\n", CsvErrorCode.MISSING_REQUIRED_COLUMNS),
        ("psi_deg,phi_deg,gain_dbi\n0,0,abc\n", CsvErrorCode.NON_NUMERIC_VALUE),
        (
            "psi_deg,phi_deg,gain_dbi\n0,0,NaN\n0,180,20\n10,0,15\n10,180,5\n",
            CsvErrorCode.NON_FINITE_VALUE,
        ),
        (
            "psi_deg,phi_deg,gain_dbi\n190,0,30\n190,180,20\n10,0,15\n10,180,5\n",
            CsvErrorCode.PSI_OUT_OF_RANGE,
        ),
        (
            "psi_deg,phi_deg,gain_dbi\n0,720,30\n0,180,20\n10,720,15\n10,180,5\n",
            CsvErrorCode.PHI_OUT_OF_RANGE,
        ),
        (
            "psi_deg,phi_deg,gain_dbi\n0,0,1\n0,0,2\n0,180,3\n10,0,4\n10,180,5\n",
            CsvErrorCode.DUPLICATE_GRID_POINT,
        ),
        (
            "psi_deg,phi_deg,gain_dbi\n0,0,30\n0,180,20\n10,0,15\n",
            CsvErrorCode.INCOMPLETE_TABLE,
        ),
        (
            "psi_deg,phi_deg,gain_dbi\n0,0,30\n0,180,20\n",
            CsvErrorCode.INSUFFICIENT_PSI_POINTS,
        ),
        (
            "psi_deg,phi_deg,gain_dbi\n0,0,30\n10,0,20\n",
            CsvErrorCode.INSUFFICIENT_PHI_POINTS,
        ),
        ("# only comments\n; still comments\n\n", CsvErrorCode.HEADER_NOT_FOUND),
        ("psi_deg,phi_deg,gain_dbi\n\n\n", CsvErrorCode.NO_DATA_ROWS),
    ],
)
def test_parse_rejects_invalid_csv_with_deterministic_code(text, code):
    with pytest.raises(CustomAntennaCsvError) as exc:
        parse_custom_antenna_csv_text(text)
    assert exc.value.code == code


def test_parse_rejects_extra_columns_with_line_number():
    text = """psi_deg,phi_deg,gain_dbi
0,0,30,999
0,180,20
10,0,15
10,180,5
"""
    with pytest.raises(CustomAntennaCsvError) as exc:
        parse_custom_antenna_csv_text(text)
    assert exc.value.code == CsvErrorCode.UNEXPECTED_COLUMN_COUNT
    assert exc.value.line_no == 2
